'use client';

import { motion } from 'framer-motion';
import { Code, Edit3, Save, Loader2 } from 'lucide-react';
import { useState, useEffect } from 'react';
import { CodeSource } from '@/types/dashboard';
import type { ContractStatus } from '@/lib/api';
import { CodeGenerationStages } from './CodeGenerationStages';
import { BuildStages } from './BuildStages';
import { AuditStages } from './AuditStages';
import { DeployStages } from './DeployStages';
import Prism from 'prismjs';
import 'prismjs/components/prism-rust';

interface InteractiveCodeEditorProps {
  initialCode?: string;
  onCodeChange: (code: string, source: CodeSource) => void;
  placeholder?: string;
  isGenerating?: boolean;
  isBuilding?: boolean;
  isAuditing?: boolean;
  isDeploying?: boolean;
  /** Live backend status — drives build/audit/deploy stage animations. */
  contractStatus?: ContractStatus | null;
  onGenerationComplete?: () => void;
  onAddAIMessage?: (message: string) => void;
  context?: string; // Context for determining contract type
  isTablet?: boolean;
  isAutoDemo?: boolean; // For auto demo mode styling
  useRealApi?: boolean; // When true, show simple loader (no demo templates)
  /** When provided, shows "Save & rebuild" button while user-edited code
   *  diverges from `initialCode`. Parent calls PUT /code + triggerBuild. */
  onSaveCode?: (code: string) => Promise<void>;
}

export const InteractiveCodeEditor = ({
  initialCode = '',
  onCodeChange,
  placeholder = "Paste your smart contract here or wait for AI to generate one...",
  isGenerating = false,
  isBuilding = false,
  isAuditing = false,
  isDeploying = false,
  contractStatus = null,
  onGenerationComplete,
  onAddAIMessage,
  context,
  isTablet = false,
  isAutoDemo = false,
  useRealApi = false,
  onSaveCode,
}: InteractiveCodeEditorProps) => {
  const addAIMessage = onAddAIMessage ?? (() => {});
  const [code, setCode] = useState(initialCode);
  const [isEditing, setIsEditing] = useState(false);
  const [source, setSource] = useState<CodeSource>('empty');
  const [isSaving, setIsSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  const hasUnsavedEdits =
    !!onSaveCode &&
    source === 'user-input' &&
    code.trim() !== '' &&
    code !== initialCode;

  const handleSaveAndRebuild = async () => {
    if (!onSaveCode || isSaving) return;
    setIsSaving(true);
    setSaveError(null);
    try {
      await onSaveCode(code);
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Save failed';
      setSaveError(msg);
    } finally {
      setIsSaving(false);
    }
  };

  // Track when code was generated by AI (not by user)
  useEffect(() => {
    if (isGenerating && initialCode) {
      setCode(initialCode);
      setSource('ai-generated');
      onCodeChange(initialCode, 'ai-generated');
    }
  }, [isGenerating, initialCode]);

  // Sync initialCode from parent only when it's not a user-edit echo-back
  useEffect(() => {
    if (initialCode !== undefined && initialCode !== code && source !== 'user-input') {
      setCode(initialCode);
      if (initialCode.trim()) {
        setSource('ai-generated');
        onCodeChange(initialCode, 'ai-generated');
      }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialCode]);

  const handleCodeChange = (newCode: string) => {
    setCode(newCode);
    const newSource: CodeSource = newCode.trim() === '' ? 'empty' : 'user-input';
    setSource(newSource);
    onCodeChange(newCode, newSource);
    
    // Force re-highlight after state update
    setTimeout(() => {
      if (typeof window !== 'undefined' && Prism.languages.rust) {
        const codeElements = document.querySelectorAll('.language-rust');
        codeElements.forEach(element => {
          if (element.textContent) {
            element.innerHTML = Prism.highlight(element.textContent, Prism.languages.rust, 'rust');
          }
        });
      }
    }, 0);
  };


  const handleGenerationComplete = (generatedCode: string) => {
    setCode(generatedCode);
    setSource('ai-generated');
    onCodeChange(generatedCode, 'ai-generated');
    onGenerationComplete?.();
  };

  const highlightCode = (code: string) => {
    if (typeof window !== 'undefined' && Prism.languages.rust) {
      try {
        return Prism.highlight(code, Prism.languages.rust, 'rust');
      } catch (error) {
        console.warn('Prism highlighting failed:', error);
        return code;
      }
    }
    return code;
  };

  // No demo/placeholder code on platform — show only real content
  const displayCode = code;

  if (isGenerating) {
    return (
      <CodeGenerationStages
        isGenerating={isGenerating}
        onComplete={handleGenerationComplete}
        onAddAIMessage={addAIMessage}
        context={context || ''}
        waitForExternalCode={useRealApi}
        contractStatus={contractStatus}
      />
    );
  }

  if (isBuilding) {
    return <BuildStages isBuilding={isBuilding} status={contractStatus} />;
  }

  if (isAuditing) {
    return <AuditStages isAuditing={isAuditing} status={contractStatus} />;
  }

  if (isDeploying) {
    return <DeployStages isDeploying={isDeploying} status={contractStatus} />;
  }

  if (!displayCode && !isEditing) {
    return (
      <div 
        className="h-full flex flex-col items-center justify-center text-center text-[#666] cursor-pointer hover:bg-[#191919] rounded-lg transition-colors"
        onClick={() => setIsEditing(true)}
      >
        <Code className="w-12 h-12 mx-auto mb-4 text-[#333]" />
        <p className="text-sm mb-2">No smart contract yet</p>
        <p className="text-xs text-[#555]">Click here to paste your code or chat with AI to generate one</p>
      </div>
    );
  }

  return (
    <>
        <style jsx global>{`
          .language-rust .token.comment { 
            color: #6a9955 !important; 
            font-style: italic;
          }
          .language-rust .token.string { 
            color: #ce9178 !important; 
          }
          .language-rust .token.keyword { 
            color: #569cd6 !important; 
            font-weight: 600;
          }
          .language-rust .token.function { 
            color: #dcdcaa !important; 
            font-weight: 500;
          }
          .language-rust .token.operator { 
            color: #d4d4d4 !important; 
            font-weight: 500;
          }
          .language-rust .token.punctuation { 
            color: #d4d4d4 !important; 
          }
          .language-rust .token.number { 
            color: #b5cea8 !important; 
          }
          .language-rust .token.boolean { 
            color: #569cd6 !important; 
            font-weight: 600;
          }
          .language-rust .token.constant { 
            color: #4fc1ff !important; 
            font-weight: 500;
          }
          .language-rust .token.attribute { 
            color: #92c5f8 !important; 
          }
          .language-rust .token.macro { 
            color: #c586c0 !important; 
            font-weight: 500;
          }
          .language-rust .token.lifetime { 
            color: #4ec9b0 !important; 
            font-weight: 500;
          }
          .language-rust .token.type { 
            color: #4ec9b0 !important; 
            font-weight: 500;
          }
          .language-rust .token.variable { 
            color: #9cdcfe !important; 
          }
          .language-rust .token.class-name { 
            color: #4ec9b0 !important; 
            font-weight: 500;
          }
          .language-rust .token.builtin { 
            color: #569cd6 !important; 
          }
          .language-rust .token.regex { 
            color: #d16969 !important; 
          }
          .language-rust .token.char { 
            color: #ce9178 !important; 
          }
          .language-rust .token.attr-name { 
            color: #92c5f8 !important; 
          }
          .language-rust .token.attr-value { 
            color: #ce9178 !important; 
          }
          .language-rust .token.namespace { 
            color: #4ec9b0 !important; 
          }
          .language-rust .token.important { 
            color: #569cd6 !important; 
            font-weight: 600;
          }
        `}</style>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex gap-3 h-full"
      >
      <div className="w-8 h-8 rounded-full bg-[#191919] flex items-center justify-center flex-shrink-0">
        {source === 'user-input' ? (
          <Edit3 className="w-4 h-4 text-blue-500" />
        ) : (
          <Code className="w-4 h-4 text-orange-500" />
        )}
      </div>
      <div className="flex-1 flex flex-col min-h-0">
            <div className="bg-[#191919] border border-[#333] rounded-lg overflow-hidden flex-1 flex flex-col relative overflow-x-hidden md:overflow-x-auto h-full">
          <>
            <div className="text-gray-400 text-xs p-3 pb-2 border-b border-[#333] flex-shrink-0">
              {`// ${source === 'user-input' ? 'Your Smart Contract' : 'Generated Smart Contract'}`}
            </div>
            <div 
              className="w-full h-full p-3 cursor-text overflow-y-auto bg-[#0a0a0a] flex flex-col code-editor"
              onClick={() => !isEditing && setIsEditing(true)}
            >
              {isEditing ? (
                <textarea
                  value={code}
                  onChange={(e) => handleCodeChange(e.target.value)}
                  onBlur={() => setIsEditing(false)}
                  placeholder={placeholder}
                  className={`flex-1 w-full bg-transparent text-gray-300 font-mono text-[9px] resize-none focus:outline-none leading-relaxed overflow-x-hidden md:overflow-x-auto whitespace-pre-wrap m-0 p-0 border-0 ${isTablet ? 'text-[8px]' : ''} ${isAutoDemo ? 'text-[7px] [word-break:break-all]' : ''}`}
                  autoFocus
                />
              ) : (
                <pre className={`flex-1 w-full font-mono text-[9px] text-gray-300 leading-relaxed whitespace-pre-wrap overflow-x-auto md:overflow-x-auto overflow-x-hidden m-0 ${isTablet ? 'text-[8px]' : ''} ${isAutoDemo ? 'text-[7px] [word-break:break-all]' : ''}`}>
                  <code 
                    className="language-rust block w-full h-full"
                    dangerouslySetInnerHTML={{ 
                      __html: highlightCode(displayCode) 
                    }}
                  />
                </pre>
              )}
            </div>
          </>
        </div>
        <div className="text-xs text-[#666] mt-1 flex-shrink-0 flex items-center justify-between gap-2">
          <span>
            {source === 'user-input' ? 'Pasted by you' : 'Generated'} • {new Date().toLocaleTimeString()}
            {saveError && (
              <span className="ml-2 text-red-400">• {saveError}</span>
            )}
          </span>
          {hasUnsavedEdits && (
            <button
              type="button"
              onClick={handleSaveAndRebuild}
              disabled={isSaving}
              className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-orange-500/15 text-orange-300 border border-orange-500/30 hover:bg-orange-500/25 hover:border-orange-500/50 disabled:opacity-50 disabled:cursor-not-allowed text-[10px] font-medium transition-colors"
            >
              {isSaving ? (
                <>
                  <Loader2 className="w-3 h-3 animate-spin" />
                  Saving…
                </>
              ) : (
                <>
                  <Save className="w-3 h-3" />
                  Save &amp; rebuild
                </>
              )}
            </button>
          )}
        </div>
      </div>
      </motion.div>
    </>
  );
};
